### ISSUE TITLE
tilemap cannot be released for jade

### ISSUE THREAD

**Issue by evenator** [swri-robotics/mapviz#440]
Could not resolve rosdep key 'libjsoncpp' for distro 'utopic':
No definition of [libjsoncpp] for OS version [utopic]
    rosdep key : libjsoncpp
    OS name    : ubuntu
    OS version : utopic
    Data: fedora:
- jsoncpp
  ubuntu:
  precise:
  - libjsoncpp0
    saucy:
  - libjsoncpp0
    trusty:
  - libjsoncpp0
    vivid:
  - libjsoncpp0
    wily:
  - libjsoncpp0v5
    xenial:
  - libjsoncpp1

**Comment by evenator** [comment]
Ditto for xenial

**Comment by pjreed** [comment]
Well, that's unfortunate.  https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml has the following for jsoncpp-related things:

```yaml
libjsoncpp:
  fedora: [jsoncpp]
  ubuntu:
    precise: [libjsoncpp0]
    saucy: [libjsoncpp0]
    trusty: [libjsoncpp0]
    vivid: [libjsoncpp0]
    wily: [libjsoncpp0v5]
    xenial: [libjsoncpp1]
libjsoncpp-dev:
  arch: [jsoncpp]
  debian: [libjsoncpp-dev]
  fedora: [jsoncpp-devel]
  gentoo:
    portage:
      packages: [dev-libs/jsoncpp]
  ubuntu: [libjsoncpp-dev]
```

So libjsoncpp is indeed missing on utopic, although it looks like it's present for xenial.
