### ISSUE TITLE
Tile map plugin - Network error 203

### ISSUE THREAD

**Issue by tynowell** [swri-robotics/mapviz#618]
Hello, 

I've got a fresh Melodic installation on Ubuntu 18.04 and I've installed mapviz (version 1.1.0) and the plugins via apt. (I have also built from source with the same results.) 

I'm having problems with the tile_map plugin. Adding a tile map, Stamen(Terrain) loads the center of the visible portion of the the map correctly but when panning out of the loaded area I get **'NETWORK ERROR: 203'** error. Some new sections load very slowly but old sections will disappear before they are out of the field of view. The faster the panning the faster the errors come so I'm guessing it might be a request frequency limitation(?). It never loads the full screen, just the central section of the FOV. The status is listed as **'OK'**.

I've also tried Bing maps (terrain) but no map sections are loaded after the api key is set. The following is my mapviz config file.

```
capture_directory: ~
fixed_frame: /wgs84
target_frame: <none>
fix_orientation: false
rotate_90: false
enable_antialiasing: true
show_displays: true
show_status_bar: true
show_capture_tools: true
window_width: 1853
window_height: 1172
view_scale: 7.187735e-05
offset_x: -10.76604
offset_y: -59.67392
use_latest_transforms: true
background: "#888a85"
displays:
  - type: mapviz_plugins/tile_map
    name: new display
    config:
      visible: true
      collapsed: false
      custom_sources:
        []
      bing_api_key: <my-bing-maps-api-key>
      source: Bing Maps (terrain)
  - type: mapviz_plugins/tile_map
    name: new display
    config:
      visible: true
      collapsed: false
      custom_sources:
        []
      bing_api_key: ""
      source: Stamen (terrain)
```

(I normal add only one tile map display at a time, this config is just to show all settings)

The effect is shown below.

![test](https://user-images.githubusercontent.com/4519360/54205418-94b39d00-44d6-11e9-9202-e5ef88c1996b.gif)

Some sections of the map (as you can see at the end of the GIF) never load.

I am also having a issue displaying GPS messages but I will create a separate issue as I don't know if they are related.
