### ISSUE TITLE
The latitude and longitude never change in Mapiz

### ISSUE THREAD

**Issue by LXlx916** [swri-robotics/mapviz#685]
Hi,  I tried to use Mapviz to plot the sensor_msgs/NavSatFix. 
My system is Ubuntu 18.04 with ROS melodic. 

First, I use roslaunch mapviz mapviz.launch to run mapviz. 
I didn't change mapviz.launch so it kept default.

```
<launch>

  <node pkg="mapviz" type="mapviz" name="mapviz"></node>

  <node pkg="swri_transform_util" type="initialize_origin.py" name="initialize_origin" >
    <param name="local_xy_frame" value="/map"/>
    <param name="local_xy_origin" value="swri"/>
    <rosparam param="local_xy_origins">
      [{ name: swri,
         latitude: 29.45196669,
         longitude: -98.61370577,
         altitude: 233.719,
         heading: 0.0},
         
       { name: back_40,
         latitude: 29.447507,
         longitude: -98.629367,
         altitude: 200.0,
         heading: 0.0}]
    </rosparam>
  </node>

  <node pkg="tf" type="static_transform_publisher" name="swri_transform" args="0 0 0 0 0 0 /map /origin 100"  />



</launch>
```

Then, I add navsat and tile_map in Mapviz like this.

![图片1](https://user-images.githubusercontent.com/45966993/82228003-19ac0900-995b-11ea-9fad-751070519c07.png)

When I played the bagfile. The latitude and longitude kept the same in Mapviz. I have read some relative Issues before. But I can't understand the reason. Maybe I missed some key steps?

This is my config.
```
capture_directory: ~
fixed_frame: map
target_frame: <none>
fix_orientation: false
rotate_90: false
enable_antialiasing: true
show_displays: true
show_status_bar: true
show_capture_tools: true
window_width: 1389
window_height: 759
view_scale: 1
offset_x: -48
offset_y: -10
use_latest_transforms: true
background: "#a0a0a4"
displays:
  - type: mapviz_plugins/navsat
    name: new display
    config:
      visible: true
      collapsed: false
      topic: /navsat/fix
      color: "#00ff00"
      draw_style: lines
      position_tolerance: 20
      buffer_size: 0
  - type: mapviz_plugins/tile_map
    name: new display
    config:
      visible: true
      collapsed: false
      custom_sources:
        []
      bing_api_key: ""
      source: Stamen (terrain)
```

Here is my bagfile.
![2](https://user-images.githubusercontent.com/45966993/82228274-82938100-995b-11ea-9251-d578d9647f28.png)

[GPS_2020-05-13-14-27-39.zip](https://github.com/swri-robotics/mapviz/files/4644825/GPS_2020-05-13-14-27-39.zip)
