### ISSUE TITLE
NETWORK ERROR: Protocol "" is unknown

### ISSUE THREAD

**Issue by tranqkhue** [swri-robotics/mapviz#722]
Hello,
My mapviz does show blank tile_map, although status is `OK` . The error is `NETWORK ERROR: Protocol "" is unknown` . My mapviz config is minimal:
```
capture_directory: "~"
fixed_frame: map
target_frame: <none>
fix_orientation: false
rotate_90: false
enable_antialiasing: true
show_displays: true
show_status_bar: true
show_capture_tools: true
window_width: 1287
window_height: 852
view_scale: 0.2709693
offset_x: 0
offset_y: 0
use_latest_transforms: true
background: "#a0a0a4"
displays:
  - type: mapviz_plugins/tile_map
    name: new display
    config:
      visible: true
      collapsed: false
      custom_sources:
        []
      bing_api_key: [hidden]
      source: Bing Maps (terrain)
```
What's this issue and how to resolve it? Thank you :D
