### ISSUE TITLE
Aligning odometry and fix messages without globally referenced heading for odometry

### ISSUE THREAD

**Issue by jmericks** [swri-robotics/mapviz#758]
![mapviz_20220522T045046_231876](https://user-images.githubusercontent.com/100721247/169679264-231d99e3-28f0-454e-b9df-3103f842f96f.png)

Ubuntu 20.04, ROS Noetic -

I am struggling with figuring out how to align my odometry messages (which come from a visual odometry (VO) algorithm running on a stereo camera) with my globally referenced GPS points. I am attempting to use GPS as ground truth for how well my VO is running. 

The VO publishes odometry message for base_link with reference to the map frame. The output is ROS standard X forward, Y left:

```
header: 
  seq: 247
  stamp: 
    secs: 1653192726
    nsecs: 689634559
  frame_id: "map"
child_frame_id: "base_link"
pose: 
  pose: 
    position: 
      x: 122.15685754202518
      y: 17.37065109891772
      z: -0.8045191563706255
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
```

I then have a GPS /fix message with frame_id "/gps" that I receive from the nmea_navsat_driver package ( https://github.com/ros-drivers/nmea_navsat_driver ). 

Neither of these messages have a globally referenced heading, wherein lies my problem. In the image above, you can see that VO outputs like its starting heading is due East, which makes sense given its starting orientation being (0,0,0,0), or due east in UTM terms. If my gps messages contained a heading, I could align the starting pose with that heading but they don't with NavSatFix messages. 
I thought maybe I needed to align the "/gps" and /"wgs84" frames, but when aligning these with a static transform, I got the following error and warning:
```
[ERROR] [1653193812.946166729]: [transform_manager]: Could not find a connection between 'wgs84' and 'map' because they are not part of the same tree.Tf has two or more unconnected trees.
[ WARN] [1653193812.946191370]: [transform_manager]: Failed to get tf transform ('map' to '/wgs84').  Both frames exist in tf.
```

To make my maps look pretty, I threw the VO Odometry message into a different frame ("VO_Frame"), and then manually guess and checked on a static transform between the map and "VO_Frame" until they were more or less aligned. Of course, this isn't a very rigorous way of going about this. 

I am wondering if anyone might have any ideas, either with other SWRI Utilities or elsewhere, where I can find a reliable way of aligning my frames so that they can be compared.
