### ISSUE TITLE
Pre-config for robot image plugin

### ISSUE THREAD

**Issue by byu-awesome-rover** [swri-robotics/mapviz#768]
Hi all,
I am trying to preset a robot image using a config file.
And doing it like below does not load the image at the beginning.
What is the way to load the `image_file`?

```
  - type: mapviz_plugins/robot_image
    name: Rover Image
    config:
      visible: true
      collapsed: false
      image_file: ~/BYU-Mars-Rover/rover_ws/src/mapviz_tf/Turtle.png
      frame: origin
      width: 50.00
      height: 50.00
      offset_x: 0
      offset_y: 0
```
