### ISSUE TITLE
I can not get tile map from Stadia

### ISSUE THREAD

**Issue by raminzare17** [swri-robotics/mapviz#846]
it did not show map, I used "https://tiles.stadiamaps.com/tiles/stamen_terrain/{z}/{x}/{y}.png?api_key=YOUR-API-KEY" with my API code that i got from stadia account.
I tested link in browers and it shows me png file,
Can problem from {z} {x} {y} that mapviz calculates?

**Comment by DangitBen** [comment]
Mapviz doesn't use the `{z}` placeholder for the zoom level. Instead it uses `{level}`. Could you try again with the following url and your API key:
`https://tiles.stadiamaps.com/tiles/stamen_terrain/{level}/{x}/{y}.png?api_key=YOUR-API-KEY`

**Comment by stevedanomodolor** [comment]
@DangitBen I am trying to use the staia terrna maps but with not success even after getting and api key. Please am I doinhg something wrong. 

![Image](https://github.com/user-attachments/assets/b5426e1d-fd98-449f-929b-e8cd6704f55d)

My config
```

capture_directory: "~"
fixed_frame: map
target_frame: map
fix_orientation: false
rotate_90: false
enable_antialiasing: true
show_displays: true
show_status_bar: true
show_capture_tools: true
window_width: 2494
window_height: 1011
view_scale: 1.77156043
offset_x: -55.0469894
offset_y: -4.65194941
use_latest_transforms: true
background: "#a0a0a4"
image_transport: raw
displays:
  - type: mapviz_plugins/tile_map
    name: new display
    config:
      visible: true
      collapsed: false
      custom_sources:
        - base_url: https://tiles.stadiamaps.com/tiles/stamen_terrain/{level}/{x}/{y}.png?api_key=XXXXXXXXXXXXXX
          max_zoom: 15
          name: Stadia
          type: wmts
      bing_api_key: ""
      source: Stadia
  - type: mapviz_plugins/point_click_publisher
    name: new display
    config:
      visible: true
      collapsed: false
      topic: clicked_point
      output_frame: wgs84
  - type: mapviz_plugins/tf_frame
    name: new display
    config:
      visible: true
      collapsed: false
      frame: base_link
      color: "#00ff00"
      draw_style: arrows
      position_tolerance: 0
      buffer_size: 1
      static_arrow_sizes: true
      arrow_size: 53
  - type: mapviz_plugins/navsat
    name: new display
    config:
      visible: true
      collapsed: false
      topic: /gps/fix
      color: "#55aaff"
      draw_style: points
      position_tolerance: 0
      buffer_size: 1
      qos_depth: 10
      qos_history: 1
      qos_reliability: 1
      qos_durability: 2
```
